### ISSUE TITLE
Parallax and Grids

### ISSUE THREAD

**Issue by char1129** [char1129/web-design-2-independent-project#1]
Hi @JessJodoin

Here's the question I asked Chelle:

"Can a parallax live within a grid? I’m having issues with the grid scrolling with the parallax. It stays static while the content scrolls in the background.
Ive tried moving the parallax into the header cell itself. Tried wrapping the body... nothing is giving me the result I need. Starting to think it’s impossible because the parallax suggests it’s a static element in behind where as the content on top scrolls at a different pace, but if I put the scroller on the body then the grid goes goodbye......

Having both grid and scroll on body causes it to float... :weary::persevere: I don’t know I’m rambling."

Your opinion?
Thank you!

Sarah

**Comment by JessJodoin** [comment]
Do you have an example of what you want it to look like so I can get a better idea of what you want it to do?

**Comment by char1129** [comment]
The look isn't the issue. It's the fact when you inspect it the grid scrolls with the page and doesn't stay in the zones the content is assigned to under inspection>grids. It's the functionality when it comes to accessibility I'm concerned because of the zone assignments. Such as jump to main section or nav etc.

BUT I do have a follow up question regarding how do I stretch the image so it takes up the whole screen in small, because I am having troubles making it take up more than the rows it requires to be 100%. Allowing the banner to be cut off at the ends in smaller screens so that the vertical height fills the initial viewport at 350px.

**Comment by JessJodoin** [comment]
For the parallax image, I think the issue might be the grid and that it's trying to scroll all together. 

What might work is removing the grid from the body because the layout seems to stay the same on different the sizes (like they're always stacked on top of each other), setting the `<div>` around the image to `position: relative;` and giving it a `z-index: -1;`, setting the `<img>` to `position: fixed;`, and making the `<main>` `position: relative;` and giving it a `z-index: 100;`. That might get it to function how you want.

For the image on small screens, you might have to play with the `object-fit` on the `<img>` and remove the `width: 100%;` and make it `height: 100%;`. And then you could add a media query for medium screens adding `width: 100%;` back and removing `height: 100%;` so that it would look like how you want on the larger screens.

Let me know if this works! 😄

**Comment by char1129** [comment]
Thank you! I'll let you know asap when I can apply it after class today :)

**Comment by char1129** [comment]
Sorry for the delay Jess. I am trying this out now. Classes have been hectic!

**Comment by char1129** [comment]
@JessJodoin 

Hi Jess,

I tried it and sadly got the same result. The flow of the site will change slightly from each query. I was focusing on perfecting the small for now before I increase size. (Design for small then go bigger - the rule of thumb).

Here are a couple screen caps of what I'm talking about.
@hellachella, thoughts?

<img width="996" alt="1" src="https://user-images.githubusercontent.com/55107755/100471273-f56a7b00-30a7-11eb-89bc-74f45b22186c.png">
<img width="982" alt="2" src="https://user-images.githubusercontent.com/55107755/100471297-00251000-30a8-11eb-93ab-236a7841d4b2.png">

**Comment by char1129** [comment]
@JessJodoin  Just spoke with Chelle. Parallax isn't good for accessibility and I'd have to use a bit of javascript to get it to work properly. So scrapping that idea! Thank you for the help!
