### ISSUE TITLE
Markbot - Hover element

### ISSUE THREAD

**Issue by char1129** [char1129/web-design-2-independent-project#4]
@JessJodoin

Hi Jess!

I'm having issue resolving the hover and nav issues with markbot.
I have a hover element working (very ugly looking but it's there for me to edit later), but markbot doesn't like it, and is also giving me this weird error message regarding 0px elements.

See picture.

Thanks! 

![errors](https://user-images.githubusercontent.com/55107755/101935529-3d5fc680-3bad-11eb-9fce-d9dd3f94dc73.JPG)

**Comment by JessJodoin** [comment]
I could be wrong but I think the last two errors are because your nav is the hamburger menu (and accessibility wise hamburger nav suck lol) [I also had this exact issue for my final web2 assignment with Chelle 😆 LOL]

What you could do is remove the hamburger nav to hand it in so it passes Markbot and then just add it back right after so when Chelle grades it, it has the nav you want.

I'm still working on the tabindex issue cause I'm not quite sure why it's doing that so I'll keep ya posted! 😄

**Comment by JessJodoin** [comment]
OH figured it out 👍 
Okay, the skip-links error is because the 'social' skip-link doesn't have a matching id tag in the index.html file (it looks like you commented it out) so all you gotta do is add it back and that should fix that error 😊 WOOP! 🙌

**Comment by char1129** [comment]
> OH figured it out 👍
> Okay, the skip-links error is because the 'social' skip-link doesn't have a matching id tag in the index.html file (it looks like you commented it out) so all you gotta do is add it back and that should fix that error 😊 WOOP! 🙌

AWESOME! Let me go tinker with it and I'll close and let you know when it's done! Thank you!!!

**Comment by char1129** [comment]
@JessJodoin The skip-links fix worked! I'll fool Markbot later when I am closer to completion and let you know midweek if hes still being a bully. Thank you Jess!
